! STUB ROUTINES FOR WHEN DDE ADD-ON IS NOT USED
      FUNCTION DDE_TEST()
      LOGICAL DDE_TEST
      DDE_TEST=.FALSE.
      RETURN
      END FUNCTION DDE_TEST
      SUBROUTINE DDE_WRAP(RES2,ILOOP,NY,Y,YDOTI,X,XEND,ITASK,ISTATE,DADT,RWORK,ZDUM,E,DIMY,DIME)
      USE PRSIZES,       ONLY: ISIZE,DPSIZE
!      
      IMPLICIT NONE
!
      INTEGER(KIND=ISIZE), INTENT(IN)     :: NY,DIMY,DIME
      INTEGER(KIND=ISIZE), INTENT(IN OUT) :: ISTATE,ILOOP,ITASK
      REAL(KIND=DPSIZE),   INTENT(IN)     :: DADT(*)
      REAL(KIND=DPSIZE),   INTENT(IN OUT) :: Y(*),X,XEND,RWORK(*),YDOTI(*),ZDUM(*),E(*)
!
      EXTERNAL RES2
      ILOOP=0
 999  CONTINUE
      RETURN
      END SUBROUTINE DDE_WRAP
